// product types
export const GET_RESTAURANTS = "GET_RESTAURANTS";
export const RESTAURANT_LOADING = "RESTAURANT_LOADING";
export const RESTAURANT_STOP_LOADING = "RESTAURANT_STOP_LOADING";
export const RESTAURANT_NOT_FOUND = "RESTAURANT_NOT_FOUND";
